
# for page centered 
.br
.EQ
Z = X + Y
.EN

# for left-justfied
.br
.EQ L
Z = X + Y
.EN

# for indented
.br
.EQ I
Z = X + Y
.EN

.EQ
f ( x , y ) = a + b x + c y + p x y + ( 1 - x ) ( 2 - y )
.EN

.EQ
f(x,y) = ({x times y} over {y times x + y}) sup 3 times sqrt {25*5}
.EN

.EQ
sin theta sub i
.EN

.EQ
sigma ~~ Sigma
.EN

.EQ
int from a to b {f(x)} ~~ dx = lim from {i~ ->~ inf} sum from {i=a} to b {f(x sub i ) Delta x sub i}
.EN
